export const membersData = [
  {
    name: "Shreehita",
    post: "Founder",
    img: "members/Shree.jpg",
    linkedin: "https://www.linkedin.com/in/sreehithathati03",
    github: "https://github.com/sreehithathati03",
  },
  {
    name: "Krish",
    post: "Founder",
    img: "members/Krish.jpg",
    linkedin: "https://www.linkedin.com/in/krish-k-498774234",
    github: "https://github.com/krishkh",
  },
  {
    name: "Sooraj",
    post: "Member",
    img: "members/Sooraj.jpg",
    linkedin: "https://www.linkedin.com/in/sooraj-bhaskar-nambiar",
    github: "https://github.com/Sooraj002",
  },
  {
    name: "Ayush",
    post: "Member",
    img: "members/Ayush.jpg",
    linkedin: "https://www.linkedin.com/in/aayush-singh-6b5978253",
  },
  {
    name: "Manisha",
    post: "Member",
    img: "members/Manisha.jpg",
    linkedin: "https://www.linkedin.com/in/manishakumari21",
  },
  {
    name: "Adista",
    post: "Member",
    img: "members/Adista.jpg",
    linkedin: "https://www.linkedin.com/in/adista-nautiyal-3011a7294",
  },
  {
    name: "Shivansh",
    post: "Member",
    img: "members/Shivansh.jpg",
    linkedin: "https://www.linkedin.com/in/shivansh-saxena-58215a29b",
    github: "https://github.com/shivansh4565",
  },
  {
    name: "Piyush",
    post: "Member",
    img: "members/Piyush.jpg",
    linkedin: "https://www.linkedin.com/in/piyush-kumar-prog",
    github: "https://github.com/piyushkumar-prog",
  },
  {
    name: "Aditya",
    post: "Member",
    img: "members/Aditya.jpg",
    linkedin: "https://www.linkedin.com/in/aditya-kumar-36454a310/",
  },
  {
    name: "Kanak",
    post: "Member",
    img: "members/Kanak.jpg",
    linkedin: "https://www.linkedin.com/in/kanak-saini-524420283",
  },
  {
    name: "Shivang Shukla",
    post: "Member",
    img: "members/Shivang.jpg",
    linkedin: "https://www.linkedin.com/in/shivang-shukla-6212012b2/",
  },
  {
    name: "Shivangi Bhartiya",
    post: "Member",
    img: "members/Shivangi.jpg",
    linkedin: "https://www.linkedin.com/in/shivangi-bhartiya-39336b294/",
    github: "https://github.com/ShivangiBhartiya",
  },
];
